### ISSUE TITLE
더보기 버튼 드롭다운 메뉴 추가

### ISSUE THREAD

**Issue by jay-noncelab** [noncelab/coconut_wallet#5]
# 🚀 Feature -  홈 화면 개선

### 📝 Description

---

- [Task-699] 홈 화면 앱바 더보기 버튼 클릭시 드롭다운 메뉴가 보여지고 사용자가 이를 선택할 수 있도록 지원
- [Task-698] 용어집을 강조하기 위해 1회 이상 진입하기 전 까지 홈 화면에 `바로가기` 버튼 추가
- [Task-704] 지갑 목록이 비워있는져 있는 경우 홈 화면에 지갑 `바로 추가하기` 버튼 추가

### ✅ To Do List

---

#### Task-699
- [ ] 드롭다운 위젯 추가
- [ ] `용어집`, `니모닉 문구 단어집`, `셀프 보안점검` / `설정`, `앱 정보 보기`를 그룹으로 나누어 드롭다운 메뉴에 추가
- [ ] 설정 페이지에서 `용어집`, `니모닉 문구 단어집`, `셀프 보안점검` 삭제
- [ ] 지갑 상세화면 더보기 버튼 아이콘 변경
- [ ] 설정 팝업으로 변경
- [ ] 니모닉 문구 단어집 페이지로 변경
- [ ] 드롭다운 메뉴 fontWeight 변경

#### Task-698
- [ ] 홈 화면 용어집 `바로가기` 버튼 추가

#### Task-704
- [ ] 홈 화면 지갑 `바로 추가하기` 버튼 추가

### 📚Etc

---
